##───────────────────────────────────────────────────##
######### ADS V2 SAMPLE CONFIGURATION BELOW #########
##───────────────────────────────────────────────────##

license: ${LICENSE:axiomatics_ADS.license}

domain:
  path: ${DOMAIN_CONFIG:domain.yaml}     # Local or HTTPS path to domain config

spring:
  security:
    user:
      name: ${ADS_USERNAME:admin}                # Use env var USERNAME
      password: ${PASSWORD:changeme}

authentication:
  enabled: false

audit:
  mode: verbose_json

logging:
  config: logback-json.xml
  level:
    root: ${LOGLEVEL:WARN}
    com.axiomatics: ${AXIOMATICS_LOGLEVEL:INFO}

    com.axiomatics.audit: ${AXIOMATICS_AUDITLOGS:INFO}